Sprint 1/step 1
mafin1799/Stellar-Burgers pull request #1
Opened 2023-08-02 13:00 UTC by mafin1799

step 1

---

Исправление ошибок

2023-08-02 13:25 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хорошая декомпозиция компонентов
- Использовали css переменные
- Хороший `codestyle` - код логичный и понятный

Необходимо исправить:
- Файл App.test.tsx необходимо удалить - он не понадобится.
- У верхней и нижней булки должны быть надписи "Верх" и "Низ" соответственно.
- В проекте много console.log
- Добавьте проверку ответа сервера - res.ok
- Использовать атрибут `style` нужно только для динамических стилей, во всех остальных случаях нужно использовать классы.
- Поправьте импорты в `react-burger/src/components/app-header/app-header.jsx`
- У всех компонентов с пропсами должны быть `propTypes`
- Использовать `var` уже не стоит (устаревший синтаксис), сейчас используется или `const` или `let`
- Файл app и стили для него должны быть в директории components

Более подробное описание некоторых замечаний - смотрите комментарии к pull-request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/App.tsx
> +        const response = await fetch('https://norma.nomoreparties.space/api/ingredients');
**Надо исправить**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответи не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/App.tsx
> +      const getProductData = async () => {
**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/App.tsx
> +      console.log(error);
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/components/app-header/app-header.jsx
> +import "@ya.praktikum/react-developer-burger-ui-components/dist/ui/fonts/fonts.css";
**Необходимо исправить**
Этот импорт в проекте не нужен. Дело в том, что если вы импортируете компонент, то вместе с ним импортируются и стили. Если вам нужны только стили, то можете сделать так
`import from '@ya.praktikum/react-developer-burger-ui-components';`

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/components/burger-ingredients/components/menu-card.jsx
> +export const MenuCard = (props) => {
**Можно улучшить**
Здесь и в коде других компонентов, лучше не писать каждый раз `props`, а использовать деструктуризацию, достав все необходимые данные из пропсов один раз. Это сделает код более понятным. https://learn.javascript.ru/destructuring#destrukturizatsiya-obekta

2023-08-02 13:25 UTC, andryxxa93 commented on react-burger/src/components/app-header/app-header.jsx
> +const NavLink = ({ path, text, pressed, children }) => {
**Можно лучше**
В будущем будет спринт посвященный роутингу, где будут использоваться компоненты react-router. Сейчас задавать активность ссылок не нужно.

2023-08-02 14:17 UTC, mafin1799 commented on react-burger/src/App.tsx
> +        const response = await fetch('https://norma.nomoreparties.space/api/ingredients');
Эту функцию и имена можно использовать для исправлений и плагиатом считаться не будет?

2023-08-03 07:38 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Промежуточная работа принята.
Вы можете приступать к финальному этапу сдачи работы!
Удачи!

2023-08-03 07:41 UTC, merged